version: "3"
services:
  master:
    build:
      context: ./mesosmaster
      dockerfile: Dockerfile
    env_file:
      - .env
    # environment:
    #   - MASTERS=${MASTERS}

  slave:
    build:
      context: ./mesosslave
      dockerfile: Dockerfile
    env_file:
      - .env
