version: "3"
services:
  master:
    build:
      context: ./mesosmaster
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # environment:
    #   - MASTERS=${MASTERS}

  slave:
    build:
      context: ./mesosslave
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
